---
- name: Installing MySQL DB
  hosts: tag_Name_DB_Server
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:     
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
    - name: MYSQL DB creation
      apt:
        name: mysql-server
        state: latest
    - name: Start MySQL service
      service:
        name: mysql
        state: started